version: "3.3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/development/Dockerfile
    container_name: backend-dev
    image: "backend-dev"
    working_dir: /app
    environment:
      - PERRY_DEPLOYMENT_MODE=development
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
