services:
  backend:
    build:
      context: ../backend
      dockerfile: ../backend/docker/development/Dockerfile
    container_name: backend-dev
    image: "backend-dev"
    working_dir: /app
    environment:
      - PERRY_DEPLOYMENT_MODE=development
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"

  frontend:
    depends_on:
      - backend
    build:
      context: ../frontend
      dockerfile: ../frontend/docker/development/Dockerfile
    container_name: frontend-dev
    image: "frontend-dev"
    working_dir: /app
    environment:
      - PERRY_DEPLOYMENT_MODE=development
    volumes:
      - ../frontend:/app
    ports:
      - "8501:8501"
