# Spin up a new instance of the server
version: "3.3"

services:
  perry:
    build:
      context: .
      dockerfile: ./compose/streamlit/Dockerfile
    container_name: perry-dev
    image: "streamlit"
    working_dir: /app
    environment:
      - PERRY_DEPLOYMENT_MODE=development
    volumes:
      - ./:/app
    ports:
      - "8501:8501"