# Spin up a new instance of the server
version: "3.3"

services:

  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.10
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  perry:
    build:
      context: .
      dockerfile: ./compose/streamlit/Dockerfile

    image: "streamlit_app"
    working_dir: /app
    environment:
      - PERRY_DEPLOYMENT_MODE=production
    volumes:
      - ./:/app
    ports:
      - "8501:8501"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.perry.rule=Host(`perry.docker.localhost`)"